# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: istio-inggate-http
#   annotations:
#     kubernetes.io/ingress.class: alb
#     alb.ingress.kubernetes.io/scheme: internet-facing
#     alb.ingress.kubernetes.io/target-type: ip    
#   namespace: istio-system
# spec:
#   rules:
#     - http:       
#         paths:
#           - path: /
#             backend:
#               serviceName: istio-ingressgateway
#               servicePort: 80

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: istio-tls
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-2:005459661421:certificate/546326b2-4ab5-4b31-aa5a-6492f09ab96d    
  namespace: istio-system
spec:
  tls:
  - hosts:
    - kong-dev.istio.dev1.eks.openshiftlabs.net
    - kong-e2e.istio.dev1.eks.openshiftlabs.net
    - kong-staging.istio.dev1.eks.openshiftlabs.net
    - kong-prd.istio.dev1.eks.openshiftlabs.net
  rules:
    - http:       
        paths:
          - path: /*
            backend:
              serviceName: istio-ingressgateway
              servicePort: 443

---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: istio-system
spec:
  mtls:
    mode: STRICT            