apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kong-staging-gateway
  annotations:  
  namespace: kong
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: kong-tls-credentials        
    hosts:
    - "kong-staging.istio.dev1.eks.openshiftlabs.net"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kong-vs
  namespace: kong
spec:
  hosts:
  - "kong-staging.istio.dev1.eks.openshiftlabs.net"
  gateways:
  - kong-staging-gateway
  http:
  - match:
    - uri:
        prefix: /amazin
    - uri:
        prefix: /products        
    route:
    - destination:
        host: global-kong-proxy.kong.svc.cluster.local
        port:
          number: 80

---
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: default
  namespace: kong
spec:
  mtls:
    mode: STRICT