# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: istio-inggate-http
#   annotations:
#     kubernetes.io/ingress.class: alb
#     alb.ingress.kubernetes.io/scheme: internet-facing
#     alb.ingress.kubernetes.io/target-type: ip    
#   namespace: istio-system
# spec:
#   rules:
#     - http:       
#         paths:
#           - path: /
#             backend:
#               serviceName: istio-ingressgateway
#               servicePort: 80

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: istio-tls
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip    
  namespace: istio-system
spec:
  rules:
    - http:       
        paths:
          - path: /*
            backend:
              serviceName: istio-ingressgateway
              servicePort: 443

---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: istio-system
spec:
  mtls:
    mode: STRICT            